// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsyTl34BuUhWPgvpNwmB0AZoqV5hu2uL4',
    appId: '1:681313559722:web:5cc0011a6546a4f51f5cd3',
    messagingSenderId: '681313559722',
    projectId: 'craneapplication-a4a13',
    authDomain: 'craneapplication-a4a13.firebaseapp.com',
    storageBucket: 'craneapplication-a4a13.firebasestorage.app',
    measurementId: 'G-NYL9BWKDC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv20YItA4Qtb-YCB-UmtyNAelM-n6UV3A',
    appId: '1:681313559722:android:ba4ad1673a5cf35d1f5cd3',
    messagingSenderId: '681313559722',
    projectId: 'craneapplication-a4a13',
    storageBucket: 'craneapplication-a4a13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFrxVq3bNVQKm4u6CfaGrXfE3C0ov5uk0',
    appId: '1:681313559722:ios:f3e0b97a46ac1bde1f5cd3',
    messagingSenderId: '681313559722',
    projectId: 'craneapplication-a4a13',
    storageBucket: 'craneapplication-a4a13.firebasestorage.app',
    iosBundleId: 'com.example.craneapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFrxVq3bNVQKm4u6CfaGrXfE3C0ov5uk0',
    appId: '1:681313559722:ios:f3e0b97a46ac1bde1f5cd3',
    messagingSenderId: '681313559722',
    projectId: 'craneapplication-a4a13',
    storageBucket: 'craneapplication-a4a13.firebasestorage.app',
    iosBundleId: 'com.example.craneapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsyTl34BuUhWPgvpNwmB0AZoqV5hu2uL4',
    appId: '1:681313559722:web:ed0252a7041292651f5cd3',
    messagingSenderId: '681313559722',
    projectId: 'craneapplication-a4a13',
    authDomain: 'craneapplication-a4a13.firebaseapp.com',
    storageBucket: 'craneapplication-a4a13.firebasestorage.app',
    measurementId: 'G-H3685LXB48',
  );
}
